name: Create JIRA Ticket

on:
  push:
    branches:
      - main  # Replace with your branch name where you want to trigger

jobs:
  create-jira-ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Choose appropriate Python version

      - name: Install requests library
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Create JIRA Ticket
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: 'https://your-domain.atlassian.net'  # Replace with your JIRA base URL
          JIRA_PROJECT_KEY: 'PROJ'  # Replace with your JIRA project key
          JIRA_ISSUE_TYPE_ID: '10001'  # Replace with your JIRA issue type ID
        run: |
          python create_jira_ticket.py $JIRA_API_TOKEN $JIRA_BASE_URL $JIRA_PROJECT_KEY $JIRA_ISSUE_TYPE_ID
